### ISSUE TITLE
Suggestion: integrate these changes into the OldUnreal patches

### ISSUE THREAD

**Issue by ahrib** [alexstrout/foxWSFix-UT99#3]
Hi there, thanks for the awesome work.

Would be great to see this integrated into the latest OldUnreal patches repo
https://github.com/OldUnreal/UnrealTournamentPatches

**Comment by alexstrout** [comment]
Just wanted to note it looks like this is being tracked at: https://github.com/OldUnreal/UnrealTournamentPatches/issues/496

I'll look into possibly submitting a PR - updating the Weapon code (if possible as a non-breaking change) would be significantly cleaner than patching things on-the-fly with this fix.

**Comment by alexstrout** [comment]
Proper weapon and FOV scaling is being integrated into the OldUnreal patches via another approach:
https://github.com/OldUnreal/UnrealTournamentPatches/issues/111#issuecomment-1869001058

This fix should no longer be needed if using those patches on release. 👍
